import model from '../../output/review/house_3d_assumptions_R01.json' with { type: 'json' };

const planAssumptions = {
  "zh": [
    "用户允许调整主体尺寸，保留三个卧室，并新增晾衣阳台。",
    "R10外轮廓8190 × 7280 mm替代旧7280 × 7280 mm，层高仍为2800 mm；均为演示假设。",
    "南侧玄关、南侧阳台与北方向均未依据场地测量。",
    "阳台6180 × 1500 mm位于主体外，净空间扣除100 mm栏杆占位。",
    "外墙180 mm、内墙100 mm，以及门窗和家具尺寸均为示意。",
    "两层厕所900 × 1700 mm在楼梯旁上下对齐；未按轮椅使用设计。",
    "楼梯16踢面×175 mm，踏面260 mm，梯宽与平台900 mm；实际净空尚待核定。",
    "房间面积包含室内设备与收纳占地；梯间为预留开洞区域。",
    "面积仅作几何比较，不是法定建筑面积或占地面积。",
    "阁楼、场地、基础、外立面及W/S/RC几何按R10重新协调；工程设计未完成。",
    "阳台支承、防水、门槛、排水及栏杆高度与锚固均待专项设计。",
    "结构、防火、采光、通风、法规、设备和地盘均未完成核验。",
    "用户于2026-10-07确认R10；具名STEP/GLB及叠加层遵循此平面。"
  ],
  "ja": [
    "ユーザーは本体寸法の調整を認め、3室の寝室と物干しバルコニーを希望しています。",
    "R10外形8190 × 7280 mmは旧7280 × 7280 mmに代わるデモ仮定です。階高2800 mmを保持します。",
    "南側玄関・南側バルコニー・北方向は、現地測量に基づかない仮定です。",
    "6180 × 1500 mmのバルコニーは本体外。内法は100 mmの手すり占有幅を除きます。",
    "外壁180 mm・内壁100 mm、建具・窓・家具は仮寸法です。",
    "両階の900 × 1700 mmトイレは階段横で上下を揃えます。車いす対応ではありません。",
    "16段×175 mm、踏面260 mm、階段・踊り場幅900 mm。実際の頭上空間は要確認です。",
    "室面積は設備・収納の占有を含みます。階段室は床開口の確保区域です。",
    "面積は幾何比較のみで、法定床面積・建築面積ではありません。",
    "小屋裏・外構・基礎・外装・W/S/RCの形状をR10に合わせます。構造計算は未実施です。",
    "バルコニー支持・防水・敷居・排水・手すり高さと固定は別途設計が必要です。",
    "構造・防火・採光・換気・法規・設備・地盤の適合は未検証です。",
    "ユーザーは2026-10-07にR10平面を承認。具名STEP/GLBと構造表示はこの配置に基づきます。"
  ],
  "en": [
    "The user permits footprint adjustment, retaining three bedrooms and adding a drying balcony.",
    "The R10 8190 × 7280 mm outline replaces the earlier 7280 × 7280 mm demonstration outline. Storeys remain 2800 mm.",
    "South entry, south balcony and north direction are assumptions without a site survey.",
    "The 6180 × 1500 mm balcony sits outside the body; clear space excludes the 100 mm railing footprint.",
    "180/100 mm walls, doors, windows and furniture dimensions are demonstration placeholders.",
    "The 900 × 1700 mm toilets align vertically beside the stairs and are not wheelchair adapted.",
    "16 risers × 175 mm, 260 mm treads, 900 mm flights and landing; actual headroom needs verification.",
    "Room areas include fixtures and storage. The stairwell is a reserved slab opening.",
    "Areas are geometric comparisons, not statutory floor or building areas.",
    "Attic, site, foundation, facade and W/S/RC geometry follow R10; engineering remains pending.",
    "Balcony support, waterproofing, threshold, drainage, guard height and anchorage need dedicated design.",
    "Structure, fire, daylight, ventilation, code, services and ground conditions have not been verified.",
    "The user approved R10 on 2026-10-07; named STEP/GLB and structural overlays follow this layout."
  ]
};
const modelTranslations = {
  "ja": [
    "外形8190 × 7280 mm、階高2800 mm、北方向・南側玄関はデモ用の仮定です。",
    "確認済みR10の室内有効境界と建具・窓の平面位置を直接利用。1・2階トイレは上下で一致します。",
    "南側バルコニー外形6180 × 1500 mm、内法幾何面積8.372㎡。共用通路からアクセスできます。東外壁まで延長し玄関の独立庇を省きます。3本の仮支持柱・基礎・手すり・排水は未計算です。",
    "床仕上げ基準はZ=0・2800 mm。仮の床スラブ厚200 mmは仕上げ面下に配置し、壁の有効高さは2600 mmです。",
    "2階床は1900 × 2720 mmの階段室全体に開口を保持します。小屋裏は厚24 mmの仮下地と18 mmの仕上げ、独立した梁・根太の構造案に変更します。",
    "建具開口高さ2100 mm、扉厚36 mm。閉位置で表示し、左右・上下に10 mmの仮の隙間を設けています。",
    "幅1000 mm超の大窓は窓台900 mm・窓高さ1300 mm。その他は窓台1500 mm・窓高さ600 mmです。",
    "窓枠見付45 mm・奥行70 mm、ガラス厚10 mm。建具・窓は未選定で、開口は下地開口寸法です。",
    "切妻屋根の棟は南北方向。勾配30度、全周軒450 mm、鉛直厚150 mmは変更可能なパラメータです。",
    "折り返し階段は16段の蹴上げ×175 mm、踏面260 mm、幅900 mm、中間踊り場奥行900 mm。各半階は7踏面と踊り場・2階床を8段目とします。",
    "階段は概念的な階段状ソリッドです。踊り場厚200 mm、上段の底面を踊り場底面と合わせて接触させています。2階床開口南端が最終蹴上げとなり、踏面を狭める追加板は設けていません。",
    "下駄箱高さ1800 mm、その他の収納家具2000 mm。配置は確認済み平面に従い、家具・住宅設備は公開寸法を参考にした独自のパラメトリック形状です。実製品は未選定です。",
    "引き戸の戸袋・階段手すり・構造接合・屋根と壁の層構成・設備システムは今後の詳細検討事項です。",
    "構造・防火・建築法規・階段の実際の頭上空間・建築確認申請要件は未検証です。",
    "暖白色外壁、木目の玄関扉、濃灰色の立ちはぜ金属切妻屋根と黒い窓枠は意匠の参考表現であり、製品は未選定です。",
    "外装厚20 mmと背後の仮の隙間2 mmは既存180 mm壁厚内に組み込み、本体の仕上げ外形8190 × 7280 mmを保持しています。",
    "連続外装で200 mm床・天井スラブ端を覆い、外側22 mmの壁厚帯のみを後退させています。ユーザー確認済み有効境界と階段開口は変わりません。",
    "窓枠を外側70 mmの壁厚帯へ移動し、平面の下地開口・窓幅・窓台・窓高さを保持しています。外側額縁と窓台水切りは個別の編集可能なソリッドです。",
    "木目の玄関扉・ハンドル・枠・ポーチと1段の踏み段はデモ用付属部品です。玄関の開口幅・高さと平面位置を保持しています。",
    "屋根の勾配30度・軒450 mm・鉛直厚150 mmを保持し、立ちはぜ・棟包み・破風・軒天・軒とい・階別のたてといを追加しています。",
    "外装・雨とい・玄関付属部品の寸法はすべてデモ用仮定です。実際の層構成・排水・構造・防火・地盤高さ・申請要件は未検証です。",
    "R10の小屋裏は収納専用のデモプランです。ユーザー確認済み1・2階の室内有効境界とR10切妻屋根外形を保持します。所在地が未指定のため、床面積不算入の認定や3階の居室としての認定は行っていません。",
    "従来の厚200 mmの概念天井板を厚24 mmの仮下地床に置き換えます。Z=5576〜5600 mmで、内法1200 × 650 mmの点検口は下地と18 mm仕上げを貫通し、仕上げ面はZ=5618 mmです。下地板だけでは耐荷力を示しません。",
    "小屋裏の床仕上げ範囲は3680 × 6880 mmです。点検開口を除く幾何投影面積24.5384㎡は法規や申請上の面積を確定するものではありません。",
    "水平天井と両側の勾配内張りを設け、仕上げ内法高さを1350 mm以下にします。水平天井の下面はZ=6968 mm、厚さ50 mm、床両端の内法高さは約1233.93 mmです。1350 mmはデモ設計目標であり、所在地の法規適合を示しません。",
    "勾配内張りには鉛直方向50 mmの表示用余裕を保持します。水平天井より上の屋根空間は収納として利用しません。断熱・換気・天井吊り・防火・層構成は今後の設計事項です。固定水平天井は候補の手法にすぎず、仕上げ天井と上部空間の計測・階数認定は所在地で確認が必要です。天井追加だけで床面積や階数から除外できるとは認定していません。",
    "両側の厚さ50 mmの腰壁、南北の厚さ20 mmの内張り、高さ650 mmの開放棚と450 mmの収納箱は独自の編集可能な仮形状で、製品は未選定です。",
    "点検はしごは展開状態を示します。幅600 mm、角度65度、高低差2818 mmで、11等分の蹴上げ約256.18 mmと10枚の踏み板を備えます。小屋裏床を最後の段とし、開口を塞ぐ追加板は設けません。",
    "展開したはしごと奥行600 mmの足元立ち位置は2階廊下を占有します。上部立ち位置の最低内法高さ約1254 mmは低い収納の点検関係のみを示し、実製品・安全な操作・同時通行は未確認です。",
    "点検口枠は厚24 mmの下地床下面に配置します。展開したふたは最小20 mmの鉛直表示間隔ではしご踏板・側桁を避け、独立した概念吊り下げ金具で接続します。施工可能な折り畳み機構ではありません。",
    "個別木材は構造の荷重伝達案を表示するものです。梁柱・床耐荷力・接合・基礎・法規の検証ではありません。所在地・地盤・荷重・材料・最終寸法は日本の建築士による確認が必要です。追加寸法はすべてデモ用仮定です。",
    "新しい敷地は10190 × 13780 mm（約140.42㎡、東西北の余白各1000 mm）と仮定します。建物配置と南側出入口はデモ用で、実測や道路資料に基づいていません。",
    "庭の仕上げ面はZ=-500 mmと仮定します。その下に厚さ50 mmの表示用面層と100 mmの概念的な地盤層を設けます。砂利・舗装・芝生の材質と厚さは変更可能です。",
    "追加のベタ基礎は厚150 mmの底盤と幅140 mmの外周立上りを保持します。R10では構造案の柱列に対応した内部支持リブを追加します。断面はすべてデモ用仮定で、配筋・地盤・支持力・耐震性・排水は今後の設計事項です。",
    "元の玄関ポーチと上段を保持し、支持部と下段を追加します。入口の高さは-500、-330、-160、-25、0 mm、段差は170、170、135、25 mmの仮定です。バリアフリーや通行に関する法規は未検証です。",
    "南側は並列2台、各2800 × 5000 mm、車両出入口は5675 mm、歩行者出入口は1800 mmと仮定します。実車の旋回、道路への接続、駐車許可は未検証です。",
    "金属フェンスは地上高さ1200 mm、支柱幅50 mmと仮定します。24枚のパネルは各9段の幅80 mm横格子と40 mmの隙間を備え、26か所の柱脚は概念表示です。接合・構造は未設計です。",
    "フェンス柱脚は300 × 300 mm、Z=-950〜-550 mmと仮定し、支柱の埋込み用に開口を設けます。地盤層と面層も対応箇所をくり抜き、各ソリッドは境界でのみ接します。実際の施工構成は未設定です。",
    "東・西・北に細い芝生を保持し、前庭の芝生を2台目の駐車区画に変更、低木は全て撤去します。基礎・庭・玄関アプローチ・フェンスは個別に表示でき、ユーザー確認済みの2階分の平面図を保持します。",
    "実際の所在地・測量・地盤調査・木材等級・荷重条件が未提供のため、構造配置はデモ案に限ります。",
    "木材・合板・コンクリートの断面寸法はすべてデモ入力で、検証による部材選定結果ではありません。",
    "柱は両階共通の閉じた壁部分に沿って上下を揃えます。2階の間仕切りだけを理由にLDKの室内有効空間へ柱を追加しません。",
    "既存の建築壁・床・屋根は表示用の外形として保持し、独立した構造案と意図的に重なります。構造表示では建築側を非表示にします。",
    "検修口下の梁は周辺の仮の補強梁で回します。接合・切欠きは幾何調整のみで、金物・部材・接合部耐力は未計算です。",
    "小屋裏の内法空間を保持するため、小屋組を厚150 mmの概念屋根帯に配置します。実際の屋根構成と部材断面は再設計・検証が必要です。",
    "収納用小屋裏が将来法定床面積に算入されないと認められても、収納荷重は建物全体の構造設計に含める必要があります。",
    "従来の1階厚200 mmの建築床表示は、設計済みの木床やコンクリート構造床ではありません。",
    "R08では独自形状の屋外灯を7台追加します。玄関外壁灯1台、アプローチ灯2台、庭園スポット灯2台、門柱灯2台です。位置・取付高さ・外形寸法・3000Kの温白色はデモ用の仮定です。",
    "玄関外壁灯の取付台は南側外壁、門柱灯の取付台は既存フェンス支柱に接します。地面の灯具のベースは庭の仕上げ面Z=-500 mmに接し、元の地盤層・基礎を変更しません。",
    "アプローチ灯2台は幅1500 mmの入口通路の西側に配置します。門柱灯の幅45 mmは支柱幅50 mm未満で、歩行者開口1800 mmと車両開口5675 mmを保持します。",
    "昼夜の光と発光拡散カバーはモデル閲覧用です。照度・まぶしさ・隣地への漏れ光・器具の防水等級・電気回路・接地・施工取付は未設計です。"
  ],
  "en": [
    "The 8190 × 7280 mm outline, 2800 mm storey height, north direction and south entrance are demonstration assumptions.",
    "Approved R10 clear room boundaries and door/window plan positions are reused directly. Toilets align between the two floors.",
    "South balcony: 6180 × 1500 mm overall, 8.372 m² clear geometric area, reached from a shared passage. It reaches the east wall and replaces the separate entry canopy. Three demonstration posts, footings, guards and drainage remain unengineered.",
    "Finished-floor datums are Z=0 and 2800 mm. The provisional 200 mm slabs sit below the finished floors; clear wall height is 2600 mm.",
    "The second-floor slab retains an opening across the full 1900 × 2720 mm stairwell. The attic uses an assumed 24 mm subfloor, 18 mm finish and a separate beam/joist structural proposal.",
    "Door openings are 2100 mm high with 36 mm leaves, shown closed with illustrative 10 mm gaps on the sides and at the top and bottom.",
    "Large windows wider than 1000 mm have 900 mm sills and 1300 mm height. Other windows have 1500 mm sills and 600 mm height.",
    "Window frames are 45 mm wide and 70 mm deep, with 10 mm glass. Door/window products are unselected; dimensions describe rough openings.",
    "The gable roof ridge runs north–south. Its 30-degree pitch, 450 mm eaves on all sides and 150 mm vertical thickness are editable parameters.",
    "The U-shaped stair has 16 risers × 175 mm, 260 mm treads, 900 mm width and a 900 mm-deep landing. Each half flight has seven treads, with the landing or second-floor surface forming the eighth level.",
    "The stairs use concept stepped solids. The landing is 200 mm thick; the upper flight bottom meets the landing bottom. The south slab-opening edge forms the final riser, without an added panel reducing tread depth.",
    "The shoe cabinet is 1800 mm high and other storage cabinets are 2100 mm high. Positions follow the user-confirmed plan; furniture and fixtures are original parametric shapes informed by public dimensions, not selected manufacturer products.",
    "Sliding-door pockets, stair handrails, structural joints, roof/wall layers and service systems need further design.",
    "Structure, fire safety, building regulations, actual stair headroom and building-confirmation application requirements have not been verified.",
    "Warm-white walls, a timber-tone entry door, a charcoal standing-seam metal gable roof and black window frames are an illustrative style; no products have been selected.",
    "The 20 mm exterior finish and illustrative 2 mm backing gap replace the outer part of the existing 180 mm wall, retaining the 8190 × 7280 mm finished building body.",
    "Continuous siding wraps the 200 mm floor and ceiling slab edges, setting back only the outer 22 mm wall-depth strip. Approved clear room boundaries and the stair opening are retained.",
    "Window frames move into the outer 70 mm wall-depth strip; rough-opening positions, widths, sills and heights remain unchanged. Exterior trims and sill flashings are separate editable solids.",
    "The timber entry leaf, handle, frame, porch and single step are demonstration accessories. Entry opening width, height and plan position remain unchanged.",
    "The original 30-degree roof pitch, 450 mm eaves and 150 mm vertical thickness are retained, with added standing seams, ridge cap, bargeboards, soffits, gutters and floor-specific downpipes.",
    "All siding, rainwater and entry-accessory dimensions are demonstration assumptions. Actual layers, drainage, structure, fire safety, ground levels and application requirements have not been verified.",
    "The R10 attic is a storage-only demonstration concept. User-confirmed first- and second-floor clear boundaries and the R10 gable envelope remain. With no specified site, it has neither approved floor-area exemption nor habitable third-storey classification.",
    "The previous 200 mm concept ceiling panel is replaced by an assumed 24 mm subfloor at Z=5576–5600 mm. A clear 1200 × 650 mm hatch passes through it and the 18 mm finish at Z=5618 mm. Subfloor thickness alone does not establish load capacity.",
    "The attic finish spans 3680 × 6880 mm. Its geometric projection excluding the hatch is 24.5384 m²; this does not establish a statutory or application area.",
    "A physical flat ceiling and side sloped linings limit finished clear height to 1350 mm. The flat ceiling underside is Z=6968 mm, its thickness is 50 mm, and deck-edge headroom is approximately 1233.93 mm. The 1350 mm limit is a demonstration target, not a local code-compliance conclusion.",
    "The sloped lining retains a 50 mm vertical display allowance. Remaining roof space above the flat ceiling is excluded from usable storage. Insulation, ventilation, ceiling suspension, fire safety and construction layers require design. The fixed ceiling is only a candidate treatment; local measurement of the finished ceiling and residual cavity, and storey classification, remain pending. Adding a ceiling alone does not establish floor-area or storey exemption.",
    "The 50 mm knee walls, 20 mm north and south linings, 650 mm open shelves and 450 mm storage boxes are original adjustable placeholders, not selected products.",
    "The access ladder is deployed, with a 600 mm width, 65-degree angle and 2818 mm rise. Eleven equal rises of approximately 256.18 mm use ten treads; the attic floor forms the last step without an extra hatch-obstructing panel.",
    "The deployed ladder and its 600 mm-deep foot standing area occupy the second-floor hall. The upper standing area has 1350 mm headroom, showing low storage access only. Actual products, safe operation and simultaneous passage remain unverified.",
    "The hatch trim follows the underside of the 24 mm subfloor. The deployed lid avoids treads and stringers with a minimum 20 mm vertical display gap and connects via individually named concept drop brackets. This is not a buildable folding mechanism.",
    "Separate timber members illustrate a load-path proposal only. They are not checks of beams, columns, floor capacity, joints, foundations or regulations. Site, soil, loads, materials and final sizes require review by a Japanese architect. All added dimensions are demonstration assumptions.",
    "The new plot is assumed to be 10190 × 13780 mm (approximately 140.42 m²; 1000 mm east/west/north margins). The building placement and south entrances are demonstration assumptions without actual survey or road information.",
    "The yard finished level is assumed to be Z=-500 mm, with a 50 mm display surface layer and a 100 mm concept soil layer below. Gravel, paving and lawn materials and thicknesses are adjustable.",
    "The concept raft retains a 150 mm slab and 140 mm perimeter stem walls. R10 adds internal support ribs aligned with the structural proposal columns. All sizes remain demonstration assumptions; reinforcement, soil, bearing capacity, seismic performance and drainage require design.",
    "The existing porch and upper step are retained, with added supports and a lower step. Entrance levels are -500, -330, -160, -25 and 0 mm; rises of 170, 170, 135 and 25 mm are demonstration values. Accessibility and passage regulations have not been verified.",
    "The south has two side-by-side parking bays, each assumed 2800 × 5000 mm, with a 5675 mm vehicle opening and an 1800 mm pedestrian opening. Actual vehicle turning, road access and parking permissions have not been verified.",
    "The metal fence is assumed to be 1200 mm above ground with 50 mm-wide posts. Each of 24 panels contains nine 80 mm horizontal slats with 40 mm gaps; 26 post bases are concept representations. Connections and structural performance have not been designed.",
    "Fence footings are assumed to be 300 × 300 mm at Z=-950 to -550 mm, with openings for embedded posts. Corresponding openings are cut in the soil and surface layers so solids meet only at boundaries. Actual construction details are not specified.",
    "Three narrow lawns remain; the front lawn becomes the second parking bay and all shrubs are removed. Foundation, yard, entrance path and fence groups can be viewed separately; user-confirmed floor plans remain unchanged.",
    "No actual building location, survey, ground investigation, timber grade or load conditions were provided; the structural layout is a demonstration proposal only.",
    "Every timber, plywood and concrete section size is a demonstration input, not a member selection derived from calculations.",
    "Columns align vertically along shared closed wall segments. Upstairs partitions alone do not justify additional columns in the clear LDK space.",
    "Existing architectural walls, floors and roof remain presentation envelopes, intentionally overlapping the independent structural proposal. Hide the architectural envelopes when viewing structure.",
    "Assumed perimeter transfer beams route the attic opening. Butt joints and notches coordinate geometry only; fasteners, hold-downs and member/connection capacity are uncalculated.",
    "Roof framing occupies the 150 mm concept roof band to preserve attic clearance. Actual roof construction and member sizes require redesign and calculation.",
    "Even if the storage attic is later accepted for statutory floor-area exclusion, its storage loads must remain part of the whole-building structural design.",
    "The original 200 mm first-floor architectural shell is not a designed timber floor or concrete load-bearing slab.",
    "R08 adds seven original outdoor fixtures: one entrance wall light, two path lights, two garden spotlights and two gate-post lights. Positions, mounting heights, housing dimensions and 3000K warm-white color are demonstration assumptions.",
    "The entrance light mounting plate touches the south facade and gate-light plates touch existing fence posts. Ground-fixture bases touch the yard finished level Z=-500 mm without changing the original soil layer or foundation.",
    "Two path lights sit west of the 1500 mm-wide entrance path. The 45 mm-wide gate lights are narrower than the 50 mm posts, preserving the 1800 mm pedestrian and 5675 mm vehicle openings.",
    "Day/night illumination and emissive diffusers are for model viewing only. Illuminance, glare, spill to neighboring sites, weatherproof rating, circuits, grounding and construction mounting have not been designed."
  ]
};
export const houseAssumptions = { zh: [...planAssumptions.zh, ...model.assumptions], ja: [...planAssumptions.ja, ...modelTranslations.ja], en: [...planAssumptions.en, ...modelTranslations.en] };
