import plan from '../../output/review/design_manifest.json' with { type: 'json' };
import model from '../../output/review/house_3d_assumptions_R01.json' with { type: 'json' };
import type { GroupId, ModelPartId, PartGroupId, PartKind } from './model-state';

export type Locale = 'zh' | 'ja' | 'en';
export const locales = ['zh', 'ja', 'en'] as const;
export const languageNames = { zh: '中文', ja: '日本語', en: 'English' } as const;
export const htmlLanguages = { zh: 'zh-CN', ja: 'ja', en: 'en' } as const;
export function isLocale(value: unknown): value is Locale {
  return typeof value === 'string' && locales.some(locale => locale === value);
}
export function resolveLocale(saved: string | null): Locale { return isLocale(saved) ? saved : 'zh'; }
export function format(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (placeholder, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : placeholder);
}

const zh = {
  models: { label: '户型方案', house: '日本两层一户建', apartment: '日本公寓 2LDK · 约 65㎡', note: '所有方案尺寸均为演示假设' },
  sceneLighting: { label: '模型昼夜', day: '白天', night: '夜晚', outdoor: '室外灯光', help: '模型昼夜独立于页面颜色模式。', fixtureHelp: '夜晚时为可见的室外灯具点灯；在部件树中可分别隐藏灯具。' },
  theme: { label: '颜色模式', system: '系统', light: '浅色', dark: '深色', help: '选择系统可跟随设备的明暗设置。' },
  app: { skip: '跳到查看区域', home: 'text-CAD 首页', nav: '房屋模型与图纸', language: '界面语言',
    title: '日本两层一户建', description: '查看日本两层一户建的参数化方案模型、平面图和可下载 CAD 文件。',
    tabs: { '3d': '三维模型', '1f': '一层平面', '2f': '二层平面', files: '文件下载' } },
  model: { region: '三维模型查看区域', title: '日本两层一户建', top: '俯视', reset: '重置视角',
    atticNote: '储物阁楼最高净高 1350 mm，为演示假设。检修梯仅表示展开状态，会占用二层走廊；可单独隐藏。法定面积与所在地用途认定待核定。',
    structureNote: '木造结构布置演示：柱、梁、土台、阁楼搁栅与开口边梁、屋架及候选承重墙。截面、荷载、连接件和基础承载尚未计算；候选墙不表示抗震等级。', demoNote: '演示方案 · 结构布置未计算；所在地、地盘、法定面积及确认申请待核定。',
    loadingViewer: '正在加载查看器…', loadingModel: '正在加载房屋模型…', selected: '已选部件', clear: '清除部件高亮',
    empty: '当前未显示部件，请勾选需要查看的部件。', gesture: '点选部件 · 拖动旋转 ·', wheel: '滚轮缩放', touch: '双指缩放',
    downloadGlb: '下载 GLB', canvas: '可旋转和缩放的房屋三维模型', fallback: '房屋模型静态预览',
    error: '当前浏览器无法显示交互模型。你仍可查看平面图或下载 GLB、STEP 文件。' },
  controls: { region: '模型控制', parts: '部件显示', cut: '剖切', enableCut: '启用剖切', height: '剖切高度', showFurniture: '显示家具', furnitureHelp: '床、沙发、桌椅与电视；不改变当前楼层和剖切高度。' },
  parameters: { title: '方案参数', units: '单位', millimetres: '毫米', outline: '外轮廓', storey: '层高', clearHeight: '净高', outlineArea: '外轮廓面积', interiorArea: '室内净面积合计', balconyArea: '阳台面积',
    note: '尺寸与结构截面均为演示假设。荷载、连接件、地基承载与法规用途待核定。' },
  groups: { structure: '结构方案', F1: '一层', F2: '二层', attic: '储物阁楼', attic_access: '阁楼检修梯（展开）', stairs: '楼梯', roof: '屋顶', foundation: '建筑基础', yard: '院子', fence: '围栏', lighting: '室外灯具', ceiling: '顶板', balcony: '阳台' },
  partKinds: { columns: '柱', beams: '梁', sills: '土台', attic_joists: '阁楼搁栅', attic_headers: '阁楼开口边梁', roof_framing: '屋架', bearing_walls: '候选承重墙', existing_plinth: '周圈基座', internal_supports: '内部基础支承', floor_slab: '楼板', external_walls: '外墙', partition_walls: '内隔墙', doors: '门', windows: '窗', storage_fixtures: '收纳柜', fixtures: '厨卫设备', furniture: '家具', guardrails: '防护栏',
    raft: '基础底板', stem_walls: '基础立上墙', entrance_supports: '玄关支承', soil: '场地土层', ground_surfaces: '砾石地面', entrance_path: '入户步道', parking: '停车位', planting: '绿化', posts: '围栏立柱', panels: '围栏面板', footings: '围栏独立基础', wall: '外墙灯', path: '步道灯', garden: '庭院灯', gate: '门口灯' },
  tree: { show: '显示{label}', collapse: '收起{label}部件', expand: '展开{label}部件', highlight: '高亮{label}',
    isolate: '单独查看{label}', alone: '单独', region: '{label}部件',
    help: '展开楼层或外构可查看分类；点击名称高亮，使用“单独”查看部件。顶部视图按钮可恢复显示。' },
  presets: { structure: '结构方案', region: '模型视图', exterior: '完整外观', first: '一层内部', second: '二层内部', attic: '阁楼内部', interior: '室内剖视' },
  rooms: { ldk: 'LDK', bath: '浴室', wash: '洗面・脱衣室', pantry: '食品储藏室', foyer: '玄关', wc: '厕所',
    hall: '走廊', stairs: '楼梯', master: '主卧', bed2: '卧室 2', bed3: '卧室 3', storage: '储藏室', balcony: '阳台' },
  plan: { sidebar: '{floor}层图纸资料', viewer: '{floor}层平面图查看区域', title: '{floor}层平面图',
    details: 'A3 横向 · 1:50 · 单位 mm', downloadDxf: '下载 DXF', openPdf: '打开两层 PDF 图纸',
    originalNote: '原始 CAD、PDF 和矢量图纸保留日文标注；下方房间表随界面语言切换。',
    areaTitle: '房间净面积', room: '房间', areaNote: '墙内净面积，含家具占地。楼梯项为梯间预留面积。',
    range: '图纸显示范围', planOnly: '只看平面', fullSheet: '完整图框', zoomOut: '缩小平面图', zoom: '平面图缩放比例',
    zoomIn: '放大平面图', fit: '适合页面', error: '矢量图纸预览无法加载，请下载 DXF 或打开 PDF。', loading: '正在加载矢量图纸…',
    previewPlan: '{floor}层平面图，日文矢量预览；包含房间名、净尺寸、面积、门号和两向7280毫米外轮廓尺寸。可切换完整图框查看面积表和假设说明。',
    previewSheet: '{floor}层完整 A3 日文矢量图纸；包含房间名、净尺寸、面积、门号、两向7280毫米外轮廓尺寸、图框、表题栏、面积表和假设说明。' },
  downloads: { title: '文件下载', revision: '当前图纸 {drawing} · 三维模型 {model}', download: '下载', sourceParameters: '阁楼与结构参数源码', source: '参数化 Python 源码',
    notes: '方案说明', assumptionsTitle: '全部方案假设',
    originalNote: '原始 CAD、PDF 和矢量图纸保留日文标注；查看器界面和房间表支持中文、日文、英文。',
    summary: '7280 × 7280 mm 外轮廓及 2800 mm 层高是演示假设。当前模型用于方案查看，结构、墙体层次、设备管线及实际楼梯净空尚待深化。',
    drafting: '平面图采用東京都建設局 CAD 製图基准的共通项目用于住宅方案，保留可编辑标注；本次输出包含 DXF、STEP、GLB、PDF，未包含 SXF 电子纳品。',
    files: {
      engineeringSource: { title: '结构与法规输入 Python 源码', detail: '可编辑的演示设计任务书；待核定输入保留为空值。' },
      engineering: { title: '结构与法规待定输入', detail: 'R06 演示参数、结构计算所需输入和所在地待核定项；不包含已完成计算。' },
      structure: { title: '可编辑结构布置方案', detail: '日文柱梁、搁栅、开口边梁和基础支承示意；截面与承载尚未计算。' },
      structurePdf: { title: '结构布置方案 PDF', detail: 'R06 补充图，标明结构方案、演示截面及待核定项目。' },
      glb: { title: 'GLB 三维模型', detail: '保留楼层与部件名称，可用于 Blender、Three.js。' },
      step: { title: 'STEP 精确实体', detail: '毫米制实体，可在 CAD 软件中继续编辑。' },
      first: { title: '一层平面', detail: '日文房间名与原生尺寸可编辑，包含 A3 纸空间。' },
      second: { title: '二层平面', detail: '日文房间名与原生尺寸可编辑，包含 A3 纸空间。' },
      attic: { title: '阁楼可编辑平面图', detail: '日文标注的储物阁楼、检修口、收纳和净高；尺寸均为演示假设。' },
      atticPdf: { title: '阁楼补充平面 PDF', detail: '独立 A3 日文补充图，包含阁楼净高与检修梯展开说明。' },
      site: { title: '院子与基础可编辑配置图', detail: '日文标注的用地、围栏、入户步道、停车位、基础与标高；尺寸均为演示假设。' },
      sitePdf: { title: '外构与基础补充 PDF', detail: '独立 A3 日文补充图，包含场地配置、基础及入口标高说明。' },
      pdf: { title: '两层 A3 图纸', detail: '日文图纸，1:50、A3 横向；打印选择实际尺寸。' },
      manifest: { title: '方案参数与假设', detail: '记录演示尺寸、房间净面积和待定项。' },
    } },
  assumptions: [...plan.assumptions, ...model.assumptions],
};

type Strings<T> = T extends string ? string : T extends readonly string[] ? readonly string[] : { [K in keyof T]: Strings<T[K]> };
export type Messages = Strings<typeof zh>;

const ja: Messages = {
  models: { label: '間取りプラン', house: '日本の2階建て戸建住宅', apartment: '日本のマンション 2LDK · 約65㎡', note: 'すべての寸法はデモ用の仮定です' },
  sceneLighting: { label: 'モデルの昼夜', day: '昼', night: '夜', outdoor: '屋外照明', help: 'モデルの昼夜はページの表示モードとは別に切り替えます。', fixtureHelp: '夜は表示中の屋外灯を点灯します。器具は部材ツリーで個別に非表示にできます。' },
  theme: { label: '表示モード', system: '自動', light: 'ライト', dark: 'ダーク', help: '自動を選ぶと端末の明暗設定に連動します。' },
  app: { skip: '閲覧エリアへ移動', home: 'text-CAD ホーム', nav: '住宅モデルと図面', language: '表示言語',
    title: '日本の2階建て戸建住宅', description: '日本の2階建て戸建住宅のパラメトリックな計画モデル、平面図、CADファイルを閲覧できます。',
    tabs: { '3d': '3Dモデル', '1f': '1階平面図', '2f': '2階平面図', files: 'ダウンロード' } },
  model: { region: '3Dモデル閲覧エリア', title: '日本の2階建て戸建住宅', top: '上面図', reset: '視点をリセット',
    atticNote: '収納用小屋裏の最高内法高さ1350 mmはデモ用の仮定です。点検はしごは展開状態のみを表し、2階廊下を占有します。個別に非表示にできます。法定面積と所在地での用途認定は未確定です。',
    structureNote: '木造の構造配置デモ：柱・梁・土台・小屋裏根太・開口補強梁・小屋組・耐力壁候補。断面・荷重・接合・基礎支持力は未計算で、候補壁は耐震等級を示しません。', demoNote: 'デモプラン · 構造配置は未計算。所在地・地盤・法定面積・建築確認は未確定です。',
    loadingViewer: 'ビューアを読み込み中…', loadingModel: '住宅モデルを読み込み中…', selected: '選択中の部材', clear: '部材の強調表示を解除',
    empty: '表示中の部材がありません。閲覧したい部材を選択してください。', gesture: '部材を選択 · ドラッグで回転 ·', wheel: 'ホイールで拡大・縮小', touch: '2本指で拡大・縮小',
    downloadGlb: 'GLBをダウンロード', canvas: '回転・拡大・縮小できる住宅の3Dモデル', fallback: '住宅モデルの静止画プレビュー',
    error: 'このブラウザでは3Dモデルを表示できません。平面図の閲覧やGLB・STEPファイルのダウンロードは可能です。' },
  controls: { region: 'モデル操作', parts: '部材の表示', cut: '水平断面', enableCut: '水平断面を有効にする', height: '切断高さ', showFurniture: '家具を表示', furnitureHelp: 'ベッド・ソファ・テーブル・椅子・テレビ。表示階と断面高さは維持します。' },
  parameters: { title: '計画パラメータ', units: '単位', millimetres: 'ミリメートル', outline: '外形寸法', storey: '階高', clearHeight: '天井高', outlineArea: '外形面積', interiorArea: '室内有効面積の合計', balconyArea: 'バルコニー面積',
    note: '寸法と部材断面はデモ用の仮定です。荷重・接合・基礎支持力・法規上の用途は未確定です。' },
  groups: { structure: '構造案', F1: '1階', F2: '2階', attic: '小屋裏収納', attic_access: '小屋裏点検はしご（展開）', stairs: '階段', roof: '屋根', foundation: '建物基礎', yard: '庭', fence: 'フェンス', lighting: '屋外照明器具', ceiling: '天井スラブ', balcony: 'バルコニー' },
  partKinds: { columns: '柱', beams: '梁', sills: '土台', attic_joists: '小屋裏根太', attic_headers: '小屋裏開口補強梁', roof_framing: '小屋組', bearing_walls: '耐力壁候補', existing_plinth: '外周の基壇', internal_supports: '内部基礎支持部', floor_slab: '床スラブ', external_walls: '外壁', partition_walls: '間仕切り壁', doors: '建具・扉', windows: '窓', storage_fixtures: '収納家具', fixtures: '住宅設備', furniture: '家具', guardrails: '手すり',
    raft: '基礎底盤', stem_walls: '基礎立上り', entrance_supports: '玄関支持部', soil: '地盤層', ground_surfaces: '砂利敷き', entrance_path: '玄関アプローチ', parking: '駐車スペース', planting: '植栽', posts: 'フェンス支柱', panels: 'フェンスパネル', footings: 'フェンス独立基礎', wall: '外壁灯', path: 'アプローチ灯', garden: '庭園灯', gate: '門灯' },
  tree: { show: '{label}を表示', collapse: '{label}の部材を折りたたむ', expand: '{label}の部材を展開', highlight: '{label}を強調表示',
    isolate: '{label}のみ表示', alone: '単独', region: '{label}の部材',
    help: '階や外構を展開すると分類を表示します。名称を選択して強調表示、「単独」でその部材だけを表示できます。上部の表示切替で全体表示に戻せます。' },
  presets: { structure: '構造案', region: 'モデルの表示切替', exterior: '建物全体', first: '1階内部', second: '2階内部', attic: '小屋裏内部', interior: '室内断面' },
  rooms: { ldk: 'LDK', bath: '浴室', wash: '洗面・脱衣室', pantry: '食品庫', foyer: '玄関', wc: 'トイレ',
    hall: '廊下', stairs: '階段', master: '主寝室', bed2: '洋室 2', bed3: '洋室 3', storage: '納戸', balcony: 'バルコニー' },
  plan: { sidebar: '{floor}階の図面情報', viewer: '{floor}階平面図の閲覧エリア', title: '{floor}階平面図',
    details: 'A3 横 · 1:50 · 単位 mm', downloadDxf: 'DXFをダウンロード', openPdf: '2階分のPDF図面を開く',
    originalNote: '元のCAD・PDF・ベクトル図面は日本語表記のままです。下の室名一覧は表示言語に連動します。',
    areaTitle: '室内の有効面積', room: '室名', areaNote: '壁内側の有効面積で、家具の占有面積を含みます。階段の数値は階段室の確保面積です。',
    range: '図面の表示範囲', planOnly: '平面図のみ', fullSheet: '図面全体', zoomOut: '平面図を縮小', zoom: '平面図の表示倍率',
    zoomIn: '平面図を拡大', fit: '画面に合わせる', error: 'ベクトル図面を読み込めません。DXFをダウンロードするか、PDFを開いてください。', loading: 'ベクトル図面を読み込み中…',
    previewPlan: '{floor}階平面図の日本語ベクトルプレビュー。室名、有効寸法、面積、建具番号、縦横7280ミリメートルの外形寸法を含みます。図面全体に切り替えると面積表と仮定条件を確認できます。',
    previewSheet: '{floor}階のA3日本語ベクトル図面全体。室名、有効寸法、面積、建具番号、縦横7280ミリメートルの外形寸法、図枠、表題欄、面積表、仮定条件を含みます。' },
  downloads: { title: 'ファイルのダウンロード', revision: '図面 {drawing} · 3Dモデル {model}', download: 'ダウンロード', sourceParameters: '小屋裏・構造パラメータのソース', source: 'パラメトリックPythonソース',
    notes: '計画の説明', assumptionsTitle: 'すべての仮定条件',
    originalNote: '元のCAD・PDF・ベクトル図面は日本語表記のままです。ビューアの操作画面と室名一覧は中国語・日本語・英語に対応しています。',
    summary: '外形7280 × 7280 mm、階高2800 mmはデモ用の仮定です。モデルは計画の閲覧用であり、構造、壁の層構成、設備配管、階段の実際の頭上空間は今後の詳細検討が必要です。',
    drafting: '住宅計画に東京都建設局CAD製図基準の共通項目を適用し、編集可能な注記を保持しています。出力はDXF・STEP・GLB・PDFで、SXFによる電子納品は含みません。',
    files: {
      engineeringSource: { title: '構造・法規入力の Python ソース', detail: '編集可能なデモ設計要件。未確定入力は空値のまま保持します。' },
      engineering: { title: '構造・法規の未確定入力', detail: 'R06の仮定、構造計算に必要な入力、所在地での未確定事項。計算済みの成果ではありません。' },
      structure: { title: '編集可能な構造配置案', detail: '柱梁・根太・開口補強梁・基礎支持部の日本語概念図。断面・耐荷力は未計算です。' },
      structurePdf: { title: '構造配置案 PDF', detail: 'R06補足図。構造案・仮断面・未確定事項を記載します。' },
      glb: { title: 'GLB 3Dモデル', detail: '階・部材名を保持。BlenderやThree.jsで利用できます。' },
      step: { title: 'STEP 精密ソリッド', detail: 'ミリメートル単位のソリッド。CADソフトで引き続き編集できます。' },
      first: { title: '1階平面図', detail: '日本語の室名・ネイティブ寸法を編集可能。A3ペーパー空間を含みます。' },
      second: { title: '2階平面図', detail: '日本語の室名・ネイティブ寸法を編集可能。A3ペーパー空間を含みます。' },
      attic: { title: '編集可能な小屋裏平面図', detail: '小屋裏収納・点検開口・収納・内法高さを日本語で表示。寸法はデモ用の仮定です。' },
      atticPdf: { title: '小屋裏補足平面図 PDF', detail: '独立したA3日本語補足図。内法高さと点検はしごの展開説明を含みます。' },
      site: { title: '編集可能な外構・基礎配置図', detail: '敷地・フェンス・玄関アプローチ・駐車場・基礎・高さを日本語で表示。寸法はデモ用の仮定です。' },
      sitePdf: { title: '外構・基礎補足図 PDF', detail: '独立したA3日本語補足図。敷地配置、基礎と入口の高さを説明します。' },
      pdf: { title: '2階分のA3図面', detail: '日本語図面、縮尺1:50・A3横。印刷時は実際のサイズを選択してください。' },
      manifest: { title: '計画パラメータと仮定条件', detail: 'デモ寸法、室内有効面積、未確定事項を記録しています。' },
    } },
  assumptions: [
    '外形7280 × 7280 mm、階高2800 mmはユーザー指定のデモ用仮定です。',
    '図面の北方向と南側玄関は表示用の仮定です。敷地・道路・現地資料は未提供です。',
    '外壁180 mm、内壁100 mm、建具・窓・家具寸法は計画上の仮寸法です。',
    '階段は16段の蹴上げ×175 mm、踏面260 mm、階段幅・中間踊り場900 mmです。',
    '室面積は壁内側の有効境界から算出し、家具占有面積を含みます。廊下面積に階段は含みません。',
    '階段面積は階段室の確保面積です。2階は床開口を含み、使用可能な床面積として扱えません。',
    '引き戸は壁内に収納する表現です。戸袋構造・枠厚は今後検討し、製品は未選定です。',
    '2階トイレ900 × 1700 mmはコンパクトです。700 mmの建具開口は平面上の寸法で、枠厚を差し引いていません。',
    '階高は各階基準面間の距離です。床スラブ・梁・仕上げ面は未設計です。',
    '切妻屋根の勾配・軒・窓台・建具高さは3D段階でデモ用パラメータを採用し、別途記録しています。',
    '構造・設備・防火・法規上の面積・階段の実際の頭上空間は未検証です。',
    'ユーザー確認済みのR01平面配置に従ってSTEP・GLBを生成しています。',
    '外形7280 × 7280 mm、階高2800 mm、北方向・南側玄関はデモ用の仮定です。',
    '確認済みR01の室内有効境界と建具・窓の平面位置を直接利用。1・2階トイレは上下で一致します。',
    '床仕上げ基準はZ=0・2800 mm。仮の床スラブ厚200 mmは仕上げ面下に配置し、壁の有効高さは2600 mmです。',
    '2階床は1900 × 2720 mmの階段室全体に開口を保持します。小屋裏は厚24 mmの仮下地と18 mmの仕上げ、独立した梁・根太の構造案に変更します。',
    '建具開口高さ2100 mm、扉厚36 mm。閉位置で表示し、左右・上下に10 mmの仮の隙間を設けています。',
    '幅1000 mm超の大窓は窓台900 mm・窓高さ1300 mm。その他は窓台1500 mm・窓高さ600 mmです。',
    '窓枠見付45 mm・奥行70 mm、ガラス厚10 mm。建具・窓は未選定で、開口は下地開口寸法です。',
    '切妻屋根の棟は南北方向。勾配30度、全周軒450 mm、鉛直厚150 mmは変更可能なパラメータです。',
    '折り返し階段は16段の蹴上げ×175 mm、踏面260 mm、幅900 mm、中間踊り場奥行900 mm。各半階は7踏面と踊り場・2階床を8段目とします。',
    '階段は概念的な階段状ソリッドです。踊り場厚200 mm、上段の底面を踊り場底面と合わせて接触させています。2階床開口南端が最終蹴上げとなり、踏面を狭める追加板は設けていません。',
    '下駄箱高さ1800 mm、その他の収納家具2100 mm。配置は確認済み平面に従い、家具・住宅設備は公開寸法を参考にした独自のパラメトリック形状です。実製品は未選定です。',
    '引き戸の戸袋・階段手すり・構造接合・屋根と壁の層構成・設備システムは今後の詳細検討事項です。',
    '構造・防火・建築法規・階段の実際の頭上空間・建築確認申請要件は未検証です。',
    '暖白色外壁、木目の玄関扉、濃灰色の立ちはぜ金属切妻屋根と黒い窓枠は意匠の参考表現であり、製品は未選定です。',
    '外装厚20 mmと背後の仮の隙間2 mmは既存180 mm壁厚内に組み込み、本体の仕上げ外形7280 × 7280 mmを保持しています。',
    '連続外装で200 mm床・天井スラブ端を覆い、外側22 mmの壁厚帯のみを後退させています。ユーザー確認済み有効境界と階段開口は変わりません。',
    '窓枠を外側70 mmの壁厚帯へ移動し、平面の下地開口・窓幅・窓台・窓高さを保持しています。外側額縁と窓台水切りは個別の編集可能なソリッドです。',
    '木目の玄関扉・ハンドル・枠・庇・ポーチと1段の踏み段はデモ用付属部品です。玄関の開口幅・高さと平面位置を保持しています。',
    '屋根の勾配30度・軒450 mm・鉛直厚150 mmを保持し、立ちはぜ・棟包み・破風・軒天・軒とい・階別のたてといを追加しています。',
    '外装・雨とい・玄関付属部品の寸法はすべてデモ用仮定です。実際の層構成・排水・構造・防火・地盤高さ・申請要件は未検証です。',
    "R06の小屋裏は収納専用のデモプランです。ユーザー確認済み1・2階の室内有効境界とR03切妻屋根外形を保持します。所在地が未指定のため、床面積不算入の認定や3階の居室としての認定は行っていません。",
    "従来の厚200 mmの概念天井板を厚24 mmの仮下地床に置き換えます。Z=5576〜5600 mmで、内法1200 × 650 mmの点検口は下地と18 mm仕上げを貫通し、仕上げ面はZ=5618 mmです。下地板だけでは耐荷力を示しません。",
    "小屋裏の床仕上げ範囲は3680 × 6880 mmです。点検開口を除く幾何投影面積24.5384㎡は法規や申請上の面積を確定するものではありません。",
    "水平天井と両側の勾配内張りを設け、仕上げ内法高さを1350 mm以下にします。水平天井の下面はZ=6968 mm、厚さ50 mm、床両端の内法高さは約971.23 mmです。1350 mmはデモ設計目標であり、所在地の法規適合を示しません。",
    "勾配内張りには鉛直方向50 mmの表示用余裕を保持します。水平天井より上の屋根空間は収納として利用しません。断熱・換気・天井吊り・防火・層構成は今後の設計事項です。固定水平天井は候補の手法にすぎず、仕上げ天井と上部空間の計測・階数認定は所在地で確認が必要です。天井追加だけで床面積や階数から除外できるとは認定していません。",
    "両側の厚さ50 mmの腰壁、南北の厚さ20 mmの内張り、高さ650 mmの開放棚と450 mmの収納箱は独自の編集可能な仮形状で、製品は未選定です。",
    "点検はしごは展開状態を示します。幅600 mm、角度65度、高低差2818 mmで、11等分の蹴上げ約256.18 mmと10枚の踏み板を備えます。小屋裏床を最後の段とし、開口を塞ぐ追加板は設けません。",
    "展開したはしごと奥行600 mmの足元立ち位置は2階廊下を占有します。上部立ち位置の内法高さ1350 mmは低い収納の点検関係のみを示し、実製品・安全な操作・同時通行は未確認です。",
    "点検口枠は厚24 mmの下地床下面に配置します。展開したふたは最小20 mmの鉛直表示間隔ではしご踏板・側桁を避け、独立した概念吊り下げ金具で接続します。施工可能な折り畳み機構ではありません。",
    "個別木材は構造の荷重伝達案を表示するものです。梁柱・床耐荷力・接合・基礎・法規の検証ではありません。所在地・地盤・荷重・材料・最終寸法は日本の建築士による確認が必要です。追加寸法はすべてデモ用仮定です。",
    '新しい敷地は11280 × 14780 mm（約166.72㎡）と仮定します。建物配置と南側出入口はデモ用で、実測や道路資料に基づいていません。',
    '庭の仕上げ面はZ=-500 mmと仮定します。その下に厚さ50 mmの表示用面層と100 mmの概念的な地盤層を設けます。砂利・舗装・芝生の材質と厚さは変更可能です。',
    '追加のベタ基礎は厚150 mmの底盤と幅140 mmの外周立上りを保持します。R06では構造案の柱列に対応した内部支持リブを追加します。断面はすべてデモ用仮定で、配筋・地盤・支持力・耐震性・排水は今後の設計事項です。',
    '元の玄関ポーチと上段を保持し、支持部と下段を追加します。入口の高さは-500、-330、-160、-25、0 mm、段差は170、170、135、25 mmの仮定です。バリアフリーや通行に関する法規は未検証です。',
    '南側の駐車区画線範囲は2800 × 5000 mm、車両出入口は3000 mm、歩行者出入口は1800 mmと仮定します。実車の旋回、道路への接続、駐車許可は未検証です。',
    '金属フェンスは地上高さ1200 mm、支柱幅50 mmと仮定します。28枚のパネルは各9段の幅80 mm横格子と40 mmの隙間を備え、30か所の柱脚は概念表示です。接合・構造は未設計です。',
    'フェンス柱脚は300 × 300 mm、Z=-950〜-550 mmと仮定し、支柱の埋込み用に開口を設けます。地盤層と面層も対応箇所をくり抜き、各ソリッドは境界でのみ接します。実際の施工構成は未設定です。',
    '4か所の芝生と3本の丸い樹冠の低木は独自の簡略化した植栽です。基礎・庭・玄関アプローチ・フェンスは個別に表示でき、ユーザー確認済みの2階分の平面図と庭配置を保持します。',
    "実際の所在地・測量・地盤調査・木材等級・荷重条件が未提供のため、構造配置はデモ案に限ります。",
    "木材・合板・コンクリートの断面寸法はすべてデモ入力で、検証による部材選定結果ではありません。",
    "柱は両階共通の閉じた壁部分に沿って上下を揃えます。2階の間仕切りだけを理由にLDKの室内有効空間へ柱を追加しません。",
    "既存の建築壁・床・屋根は表示用の外形として保持し、独立した構造案と意図的に重なります。構造表示では建築側を非表示にします。",
    "概念の突き付け接合・避け切りは幾何調整のみで、締結金具・引抜き金物・接合部耐力は未設計です。",
    "小屋裏の内法空間を保持するため、小屋組を厚150 mmの概念屋根帯に配置します。実際の屋根構成と部材断面は再設計・検証が必要です。",
    "収納用小屋裏が将来法定床面積に算入されないと認められても、収納荷重は建物全体の構造設計に含める必要があります。",
    "従来の1階厚200 mmの建築床表示は、設計済みの木床やコンクリート構造床ではありません。",
    'R08では独自形状の屋外灯を7台追加します。玄関外壁灯1台、アプローチ灯2台、庭園スポット灯2台、門柱灯2台です。位置・取付高さ・外形寸法・3000Kの温白色はデモ用の仮定です。',
    '玄関外壁灯の取付台は南側外壁、門柱灯の取付台は既存フェンス支柱に接します。地面の灯具のベースは庭の仕上げ面Z=-500 mmに接し、元の地盤層・基礎を変更しません。',
    'アプローチ灯2台は幅1500 mmの入口通路の西側に配置します。門柱灯の幅45 mmは支柱幅50 mm未満で、歩行者開口1800 mmと車両開口3000 mmを保持します。',
    '昼夜の光と発光拡散カバーはモデル閲覧用です。照度・まぶしさ・隣地への漏れ光・器具の防水等級・電気回路・接地・施工取付は未設計です。',
  ],
};

const en: Messages = {
  models: { label: 'Layout', house: 'Japanese two-storey house', apartment: 'Japanese apartment 2LDK · approx. 65 m²', note: 'All plan dimensions are demonstration assumptions' },
  sceneLighting: { label: 'Model time of day', day: 'Day', night: 'Night', outdoor: 'Outdoor lights', help: 'Model time of day is independent of the page color mode.', fixtureHelp: 'Lights visible outdoor fixtures at night. Hide fixtures separately in the component tree.' },
  theme: { label: 'Color mode', system: 'Auto', light: 'Light', dark: 'Dark', help: 'Auto follows your device’s light or dark appearance.' },
  app: { skip: 'Skip to viewer', home: 'text-CAD home', nav: 'House model and drawings', language: 'Interface language',
    title: 'Japanese two-storey house', description: 'Explore a parametric concept model, floor plans and downloadable CAD files for a Japanese two-storey house.',
    tabs: { '3d': '3D model', '1f': 'First-floor plan', '2f': 'Second-floor plan', files: 'Downloads' } },
  model: { region: '3D model viewer', title: 'Japanese two-storey house', top: 'Top view', reset: 'Reset view',
    atticNote: 'Storage attic with a demonstration maximum clear height of 1350 mm. The ladder shows its deployed state and occupies the second-floor hall; hide it separately. Statutory area and local use classification remain pending.',
    structureNote: 'Timber structural layout demonstration: columns, beams, sills, attic joists, hatch headers, roof framing and candidate bearing walls. Member sizes, loads, connections and foundation capacity are uncalculated; wall candidates do not indicate a seismic rating.', demoNote: 'Demonstration concept · Structural layout is uncalculated. Site, soil, statutory area and building approval remain pending.',
    loadingViewer: 'Loading viewer…', loadingModel: 'Loading house model…', selected: 'Selected component', clear: 'Clear component highlight',
    empty: 'No components are visible. Select the components you want to view.', gesture: 'Select a component · Drag to rotate ·', wheel: 'Scroll to zoom', touch: 'Pinch to zoom',
    downloadGlb: 'Download GLB', canvas: 'House 3D model with rotation and zoom controls', fallback: 'Static house model preview',
    error: 'This browser cannot display the interactive model. You can still view the floor plans or download the GLB and STEP files.' },
  controls: { region: 'Model controls', parts: 'Component visibility', cut: 'Cutaway', enableCut: 'Enable cutaway', height: 'Cut height', showFurniture: 'Furniture', furnitureHelp: 'Beds, sofas, tables, chairs and TVs. Keeps the current floor and cut height.' },
  parameters: { title: 'Concept parameters', units: 'Units', millimetres: 'Millimetres', outline: 'Building outline', storey: 'Storey height', clearHeight: 'Clear height', outlineArea: 'Outline area', interiorArea: 'Total net interior area', balconyArea: 'Balcony area',
    note: 'Dimensions and member sizes are demonstration assumptions. Loads, connections, foundation capacity and regulatory use remain pending.' },
  groups: { structure: 'Structural scheme', F1: 'First floor', F2: 'Second floor', attic: 'Attic storage', attic_access: 'Attic access ladder (deployed)', stairs: 'Stairs', roof: 'Roof', foundation: 'Building foundation', yard: 'Yard', fence: 'Fence', lighting: 'Outdoor light fixtures', ceiling: 'Ceiling slab', balcony: 'Balcony' },
  partKinds: { columns: 'Columns', beams: 'Beams', sills: 'Sills', attic_joists: 'Attic joists', attic_headers: 'Attic hatch headers', roof_framing: 'Roof framing', bearing_walls: 'Candidate bearing walls', existing_plinth: 'Perimeter plinth', internal_supports: 'Internal foundation supports', floor_slab: 'Floor slab', external_walls: 'External walls', partition_walls: 'Partitions', doors: 'Doors', windows: 'Windows', storage_fixtures: 'Storage cabinets', fixtures: 'Kitchen and bathroom fixtures', furniture: 'Furniture', guardrails: 'Guardrails',
    raft: 'Foundation slabs', stem_walls: 'Stem walls', entrance_supports: 'Entrance supports', soil: 'Soil layer', ground_surfaces: 'Gravel surface', entrance_path: 'Entrance path', parking: 'Parking space', planting: 'Planting', posts: 'Fence posts', panels: 'Fence panels', footings: 'Fence footings', wall: 'Wall lights', path: 'Path lights', garden: 'Garden lights', gate: 'Gate lights' },
  tree: { show: 'Show {label}', collapse: 'Collapse {label} components', expand: 'Expand {label} components', highlight: 'Highlight {label}',
    isolate: 'View only {label}', alone: 'Only', region: '{label} components',
    help: 'Expand a floor or site group to see its categories. Select a name to highlight it, or use “Only” to isolate it. The view presets above restore the display.' },
  presets: { structure: 'Structural scheme', region: 'Model views', exterior: 'Whole house', first: 'First-floor interior', second: 'Second-floor interior', attic: 'Attic interior', interior: 'Interior cutaway' },
  rooms: { ldk: 'Living / dining / kitchen', bath: 'Bathroom', wash: 'Washroom / changing room', pantry: 'Pantry', foyer: 'Entrance', wc: 'Toilet',
    hall: 'Hallway', stairs: 'Stairs', master: 'Main bedroom', bed2: 'Bedroom 2', bed3: 'Bedroom 3', storage: 'Storeroom', balcony: 'Balcony' },
  plan: { sidebar: 'Floor {floor} drawing information', viewer: 'Floor {floor} plan viewer', title: 'Floor {floor} plan',
    details: 'A3 landscape · 1:50 · Units mm', downloadDxf: 'Download DXF', openPdf: 'Open both floors as PDF',
    originalNote: 'The original CAD, PDF and vector drawings retain Japanese annotations. The room table below follows the interface language.',
    areaTitle: 'Net room areas', room: 'Room', areaNote: 'Net areas inside walls, including furniture footprints. The stairs entry is the reserved stairwell area.',
    range: 'Drawing view', planOnly: 'Plan only', fullSheet: 'Full sheet', zoomOut: 'Zoom out of plan', zoom: 'Plan zoom level',
    zoomIn: 'Zoom into plan', fit: 'Fit to page', error: 'The vector preview could not be loaded. Download the DXF or open the PDF.', loading: 'Loading vector drawing…',
    previewPlan: 'Floor {floor} plan, a Japanese vector preview with room names, clear dimensions, areas, door numbers and a 7280-millimetre outline in both directions. Switch to the full sheet for the area schedule and assumptions.',
    previewSheet: 'Floor {floor} full A3 Japanese vector drawing with room names, clear dimensions, areas, door numbers, a 7280-millimetre outline in both directions, drawing frame, title block, area schedule and assumptions.' },
  downloads: { title: 'File downloads', revision: 'Drawings {drawing} · 3D model {model}', download: 'Download', sourceParameters: 'Attic and structural parameter source', source: 'Parametric Python source',
    notes: 'Concept notes', assumptionsTitle: 'All design assumptions',
    originalNote: 'The original CAD, PDF and vector drawings retain Japanese annotations. Viewer controls and room tables support Chinese, Japanese and English.',
    summary: 'The 7280 × 7280 mm outline and 2800 mm storey height are demonstration assumptions. This model is for concept review; structure, wall layers, building services and actual stair headroom need further design.',
    drafting: 'The residential concept uses the common provisions of the Tokyo Metropolitan Government Bureau of Construction CAD drafting standard and retains editable annotations. Outputs include DXF, STEP, GLB and PDF; SXF electronic submission is not included.',
    files: {
      engineeringSource: { title: 'Structural and regulatory input Python source', detail: 'Editable demonstration design brief. Pending inputs remain null.' },
      engineering: { title: 'Pending structural and regulatory inputs', detail: 'R06 assumptions, inputs required for structural calculations and pending local decisions. No completed calculation is included.' },
      structure: { title: 'Editable structural layout scheme', detail: 'Japanese concept drawings of columns, beams, joists, hatch headers and foundation supports. Sizes and capacity are uncalculated.' },
      structurePdf: { title: 'Structural layout scheme PDF', detail: 'R06 supplementary drawing with the structural proposal, assumed sizes and pending verification items.' },
      glb: { title: 'GLB 3D model', detail: 'Retains floor and component names for use in Blender and Three.js.' },
      step: { title: 'STEP exact solids', detail: 'Millimetre-based solids for further editing in CAD software.' },
      first: { title: 'First-floor plan', detail: 'Editable Japanese room names and native dimensions, with A3 paper space.' },
      second: { title: 'Second-floor plan', detail: 'Editable Japanese room names and native dimensions, with A3 paper space.' },
      attic: { title: 'Editable attic plan', detail: 'Japanese annotations for attic storage, hatch, cabinets and clear heights; dimensions are demonstration assumptions.' },
      atticPdf: { title: 'Supplementary attic plan PDF', detail: 'A separate A3 Japanese drawing with attic clear heights and the deployed access-ladder note.' },
      site: { title: 'Editable yard and foundation layout', detail: 'Japanese annotations for the plot, fence, entrance path, parking, foundation and levels; all dimensions are demonstration assumptions.' },
      sitePdf: { title: 'Supplementary site and foundation PDF', detail: 'A separate A3 Japanese drawing showing the site layout, foundation and entrance levels.' },
      pdf: { title: 'Both floors on A3 sheets', detail: 'Japanese drawings, 1:50, A3 landscape. Print at actual size.' },
      manifest: { title: 'Parameters and assumptions', detail: 'Records demonstration dimensions, net room areas and unresolved details.' },
    } },
  assumptions: [
    'The 7280 × 7280 mm outline and 2800 mm storey height are user-specified demonstration assumptions.',
    'Drawing north and the south entrance are display assumptions. Site, road and survey information has not been supplied.',
    'The 180 mm external walls, 100 mm partitions, door/window dimensions and furniture dimensions are concept placeholders.',
    'The stairs have 16 risers × 175 mm, 260 mm treads, a 900 mm flight width and a 900 mm intermediate landing.',
    'Room areas use clear boundaries inside walls and include furniture footprints. Hallway areas exclude the stairs.',
    'The stairs area is reserved stairwell space. The second floor includes a slab opening and must not be counted as usable floor area.',
    'Sliding doors are shown retracting into walls. Pocket construction and frame thickness need further design; products have not been selected.',
    'The second-floor toilet is compact at 900 × 1700 mm. Its 700 mm door opening is a plan dimension before frame allowances.',
    'Storey height is the distance between floor datums. Slabs, beams and finished surfaces have not been designed.',
    'Demonstration roof pitch, eaves, window sills and door/window heights were adopted at the 3D stage and recorded separately.',
    'Structure, services, fire safety, legally defined areas and actual stair headroom have not been verified.',
    'The user approved the R01 floor layout; STEP and GLB were generated from that layout.',
    'The 7280 × 7280 mm outline, 2800 mm storey height, north direction and south entrance are demonstration assumptions.',
    'Approved R01 clear room boundaries and door/window plan positions are reused directly. Toilets align between the two floors.',
    'Finished-floor datums are Z=0 and 2800 mm. The provisional 200 mm slabs sit below the finished floors; clear wall height is 2600 mm.',
    'The second-floor slab retains an opening across the full 1900 × 2720 mm stairwell. The attic uses an assumed 24 mm subfloor, 18 mm finish and a separate beam/joist structural proposal.',
    'Door openings are 2100 mm high with 36 mm leaves, shown closed with illustrative 10 mm gaps on the sides and at the top and bottom.',
    'Large windows wider than 1000 mm have 900 mm sills and 1300 mm height. Other windows have 1500 mm sills and 600 mm height.',
    'Window frames are 45 mm wide and 70 mm deep, with 10 mm glass. Door/window products are unselected; dimensions describe rough openings.',
    'The gable roof ridge runs north–south. Its 30-degree pitch, 450 mm eaves on all sides and 150 mm vertical thickness are editable parameters.',
    'The U-shaped stair has 16 risers × 175 mm, 260 mm treads, 900 mm width and a 900 mm-deep landing. Each half flight has seven treads, with the landing or second-floor surface forming the eighth level.',
    'The stairs use concept stepped solids. The landing is 200 mm thick; the upper flight bottom meets the landing bottom. The south slab-opening edge forms the final riser, without an added panel reducing tread depth.',
    'The shoe cabinet is 1800 mm high and other storage cabinets are 2100 mm high. Positions follow the user-confirmed plan; furniture and fixtures are original parametric shapes informed by public dimensions, not selected manufacturer products.',
    'Sliding-door pockets, stair handrails, structural joints, roof/wall layers and service systems need further design.',
    'Structure, fire safety, building regulations, actual stair headroom and building-confirmation application requirements have not been verified.',
    'Warm-white walls, a timber-tone entry door, a charcoal standing-seam metal gable roof and black window frames are an illustrative style; no products have been selected.',
    'The 20 mm exterior finish and illustrative 2 mm backing gap replace the outer part of the existing 180 mm wall, retaining the 7280 × 7280 mm finished building body.',
    'Continuous siding wraps the 200 mm floor and ceiling slab edges, setting back only the outer 22 mm wall-depth strip. Approved clear room boundaries and the stair opening are retained.',
    'Window frames move into the outer 70 mm wall-depth strip; rough-opening positions, widths, sills and heights remain unchanged. Exterior trims and sill flashings are separate editable solids.',
    'The timber entry leaf, handle, frame, canopy, porch and single step are demonstration accessories. Entry opening width, height and plan position remain unchanged.',
    'The original 30-degree roof pitch, 450 mm eaves and 150 mm vertical thickness are retained, with added standing seams, ridge cap, bargeboards, soffits, gutters and floor-specific downpipes.',
    'All siding, rainwater and entry-accessory dimensions are demonstration assumptions. Actual layers, drainage, structure, fire safety, ground levels and application requirements have not been verified.',
    "The R06 attic is a storage-only demonstration concept. User-confirmed first- and second-floor clear boundaries and the R03 gable envelope remain. With no specified site, it has neither approved floor-area exemption nor habitable third-storey classification.",
    "The previous 200 mm concept ceiling panel is replaced by an assumed 24 mm subfloor at Z=5576–5600 mm. A clear 1200 × 650 mm hatch passes through it and the 18 mm finish at Z=5618 mm. Subfloor thickness alone does not establish load capacity.",
    "The attic finish spans 3680 × 6880 mm. Its geometric projection excluding the hatch is 24.5384 m²; this does not establish a statutory or application area.",
    "A physical flat ceiling and side sloped linings limit finished clear height to 1350 mm. The flat ceiling underside is Z=6968 mm, its thickness is 50 mm, and deck-edge headroom is approximately 971.23 mm. The 1350 mm limit is a demonstration target, not a local code-compliance conclusion.",
    "The sloped lining retains a 50 mm vertical display allowance. Remaining roof space above the flat ceiling is excluded from usable storage. Insulation, ventilation, ceiling suspension, fire safety and construction layers require design. The fixed ceiling is only a candidate treatment; local measurement of the finished ceiling and residual cavity, and storey classification, remain pending. Adding a ceiling alone does not establish floor-area or storey exemption.",
    "The 50 mm knee walls, 20 mm north and south linings, 650 mm open shelves and 450 mm storage boxes are original adjustable placeholders, not selected products.",
    "The access ladder is deployed, with a 600 mm width, 65-degree angle and 2818 mm rise. Eleven equal rises of approximately 256.18 mm use ten treads; the attic floor forms the last step without an extra hatch-obstructing panel.",
    "The deployed ladder and its 600 mm-deep foot standing area occupy the second-floor hall. The upper standing area has 1350 mm headroom, showing low storage access only. Actual products, safe operation and simultaneous passage remain unverified.",
    "The hatch trim follows the underside of the 24 mm subfloor. The deployed lid avoids treads and stringers with a minimum 20 mm vertical display gap and connects via individually named concept drop brackets. This is not a buildable folding mechanism.",
    "Separate timber members illustrate a load-path proposal only. They are not checks of beams, columns, floor capacity, joints, foundations or regulations. Site, soil, loads, materials and final sizes require review by a Japanese architect. All added dimensions are demonstration assumptions.",
    'The new plot is assumed to be 11280 × 14780 mm (approximately 166.72 m²). The building placement and south entrances are demonstration assumptions without actual survey or road information.',
    'The yard finished level is assumed to be Z=-500 mm, with a 50 mm display surface layer and a 100 mm concept soil layer below. Gravel, paving and lawn materials and thicknesses are adjustable.',
    'The concept raft retains a 150 mm slab and 140 mm perimeter stem walls. R06 adds internal support ribs aligned with the structural proposal columns. All sizes remain demonstration assumptions; reinforcement, soil, bearing capacity, seismic performance and drainage require design.',
    'The existing porch and upper step are retained, with added supports and a lower step. Entrance levels are -500, -330, -160, -25 and 0 mm; rises of 170, 170, 135 and 25 mm are demonstration values. Accessibility and passage regulations have not been verified.',
    'The south parking boundary lines enclose an assumed 2800 × 5000 mm space, with a 3000 mm vehicle opening and an 1800 mm pedestrian opening. Actual vehicle turning, road access and parking permissions have not been verified.',
    'The metal fence is assumed to be 1200 mm above ground with 50 mm-wide posts. Each of 28 panels contains nine 80 mm horizontal slats with 40 mm gaps; 30 post bases are concept representations. Connections and structural performance have not been designed.',
    'Fence footings are assumed to be 300 × 300 mm at Z=-950 to -550 mm, with openings for embedded posts. Corresponding openings are cut in the soil and surface layers so solids meet only at boundaries. Actual construction details are not specified.',
    'Four lawn patches and three shrubs with rounded crowns are original simplified planting shapes. Foundation, yard, entrance path and fence groups can be viewed separately; user-confirmed floor plans and yard layout remain unchanged.',
    "No actual building location, survey, ground investigation, timber grade or load conditions were provided; the structural layout is a demonstration proposal only.",
    "Every timber, plywood and concrete section size is a demonstration input, not a member selection derived from calculations.",
    "Columns align vertically along shared closed wall segments. Upstairs partitions alone do not justify additional columns in the clear LDK space.",
    "Existing architectural walls, floors and roof remain presentation envelopes, intentionally overlapping the independent structural proposal. Hide the architectural envelopes when viewing structure.",
    "Concept butt joints and avoidance notches coordinate geometry only; fasteners, hold-downs and connection capacities are undesigned.",
    "Roof framing occupies the 150 mm concept roof band to preserve attic clearance. Actual roof construction and member sizes require redesign and calculation.",
    "Even if the storage attic is later accepted for statutory floor-area exclusion, its storage loads must remain part of the whole-building structural design.",
    "The original 200 mm first-floor architectural shell is not a designed timber floor or concrete load-bearing slab.",
    'R08 adds seven original outdoor fixtures: one entrance wall light, two path lights, two garden spotlights and two gate-post lights. Positions, mounting heights, housing dimensions and 3000K warm-white color are demonstration assumptions.',
    'The entrance light mounting plate touches the south facade and gate-light plates touch existing fence posts. Ground-fixture bases touch the yard finished level Z=-500 mm without changing the original soil layer or foundation.',
    'Two path lights sit west of the 1500 mm-wide entrance path. The 45 mm-wide gate lights are narrower than the 50 mm posts, preserving the 1800 mm pedestrian and 3000 mm vehicle openings.',
    'Day/night illumination and emissive diffusers are for model viewing only. Illuminance, glare, spill to neighboring sites, weatherproof rating, circuits, grounding and construction mounting have not been designed.',
  ],
};

export const messages: Record<Locale, Messages> = { zh, ja, en };

export function selectionLabel(copy: Messages, id: ModelPartId): string {
  if (!id.includes(':')) return copy.groups[id as GroupId];
  const [group, kind] = id.split(':') as [PartGroupId, PartKind];
  return `${copy.groups[group]} · ${copy.partKinds[kind]}`;
}
export function roomLabel(copy: Messages, id: string): string {
  return copy.rooms[id as keyof Messages['rooms']] ?? id;
}
