import type { Locale, Messages } from './localization';
import type { ModelId } from './model-state';

const apartment = {
  zh: {
    bedroom1: '卧室 1', title: '日本公寓 · 2LDK', description: '约 65㎡ 日本公寓 2LDK 演示方案：两间卧室、LDK、独立厨卫及南侧阳台。查看参数化模型、平面图和 CAD 文件。',
    plan: '公寓平面', planTitle: '2LDK 公寓平面图', pdf: '打开公寓 PDF 图纸', complete: '完整户型', interior: '公寓室内',
    areaNote: '房间净面积含柜体与设备占地；阳台单列，不计入室内净面积。外轮廓面积 65.52㎡，不等于内法面积。',
    parameterNote: '演示假设；65.52㎡为外轮廓面积，阳台另计。结构和设备管线尚未设计。',
    preview: '2LDK 公寓日文平面图：房间名、净尺寸、面积、门窗、7800 × 8400毫米外轮廓及南侧阳台。',
    summary: '本方案为日本单层公寓 2LDK 演示户型。7800 × 8400 mm 外轮廓、2800 mm 层高、2500 mm 净高及 7800 × 1500 mm 南侧阳台均为演示假设。65.52㎡为外轮廓面积，不是内法面积；阳台另计。',
    drafting: '包含可编辑日文房间名与尺寸的 DXF、实体 STEP、分组 GLB 以及 A3 PDF。图纸为方案草案，结构、消防、设备、场地条件及法规符合性尚未核验。',
    planDetail: '单层 2LDK，日文房间名与尺寸可编辑，包含南侧阳台。', pdfTitle: '公寓 A3 平面图', pdfDetail: '单页日文图纸，A3 横向、1:50；打印选择实际尺寸。',
    assumptions: [
      "7800 × 8400 mm 外轮廓、2800 mm 层高、2500 mm 室内净高及全部细部尺寸均为演示假设。",
      "65.52㎡是本示例外轮廓投影面积，包含外墙与隔墙，不代表房产登记面积、专有面积或法定建筑面积。",
      "56.54㎡是房间净边界面积之和，包含柜体和设备占地，排除所有墙体和阳台。",
      "11.70㎡阳台为7800 × 1500 mm示意板面投影，单独计算，包含栏板投影。",
      "北侧公共走廊入户、南侧阳台及北向均为展示假设，未提供地块或整栋建筑资料。",
      "外墙/户间墙200 mm、室内隔墙100 mm，楼板200 mm；模型为单一住户，无内部楼梯和坡屋顶。",
      "中部走廊宽1400 mm；玄关鞋柜深350 mm后剩余通行宽1050 mm。",
      "两卧室北侧设高窗，LDK南侧设两组落地移门通向阳台；户间墙无侧窗。",
      "玄关高差用分界线示意；模型完成面统一Z=0，未生成防水、排水坡度或门槛构造。",
      "室内门洞700/750/800 mm；移门使用外挂轨道概念并留出墙边空间，门洞为毛洞尺寸。",
      "浴室1400 × 1800 mm、洗面脱衣1600 × 1800 mm、厕所1000 × 1800 mm为方案预留。",
      "顶板及阳台栏板仅表达外形；门窗、柜体、卫生设备均为概念占位，未选实际产品。",
      "顶板为Z=2500至2700 mm；至2800 mm楼层基准面余100 mm层间构造未建模。",
      "未验证结构、采光通风、消防疏散、设备管井、阳台隔板或日本建筑确认申报要求。",
    ],
  },
  ja: {
    bedroom1: '洋室 1', title: '日本のマンション · 2LDK', description: '約65㎡の2LDKマンションのデモプラン。2室の洋室、LDK、水回り、南側バルコニーのパラメトリックモデル・平面図・CADファイルを閲覧できます。',
    plan: '住戸平面図', planTitle: '2LDK マンション平面図', pdf: '住戸のPDF図面を開く', complete: '住戸全体', interior: '住戸内部',
    areaNote: '室内有効面積は収納・設備の占有面積を含みます。バルコニーは別計上です。外形面積65.52㎡は内法面積ではありません。',
    parameterNote: 'デモ用の仮定です。65.52㎡は外形面積、バルコニーは別計上です。構造・設備配管は未設計です。',
    preview: '2LDK住戸の日本語平面図。室名、有効寸法、面積、建具、7800 × 8400ミリメートルの外形寸法と南側バルコニーを表示。',
    summary: '日本の単層マンション2LDKのデモプランです。外形7800 × 8400 mm、階高2800 mm、天井高2500 mm、南側バルコニー7800 × 1500 mmは仮定です。65.52㎡は外形面積であり、内法面積ではありません。バルコニーは別計上です。',
    drafting: '編集可能な日本語室名・寸法のDXF、ソリッドSTEP、部材を分類したGLB、A3 PDFを含みます。計画図のため、構造・防火・設備・敷地条件・法規適合性は未検証です。',
    planDetail: '単層2LDK。日本語室名と寸法を編集可能で、南側バルコニーを含みます。', pdfTitle: '住戸のA3平面図', pdfDetail: '日本語の1枚図面、A3横・1:50。印刷時は実際のサイズを選択してください。',
    assumptions: [
      "外形7800 × 8400 mm、階高2800 mm、天井高2500 mmを含むすべての寸法はデモ用の仮定です。",
      "65.52㎡は外壁・間仕切りを含む外形投影面積です。登記面積、専有面積または法定の床面積ではありません。",
      "56.54㎡は各室の有効境界の面積合計です。収納・設備の占有面積を含み、壁とバルコニーを除きます。",
      "バルコニー11.70㎡は7800 × 1500 mmの概念的な床面投影で、腰壁の投影を含めて別計上します。",
      "北側共用廊下からの入居、南側バルコニー、北の方位は表示用の仮定です。敷地や建物全体の資料は未提供です。",
      "外壁・戸境壁200 mm、間仕切り100 mm、床スラブ200 mm。1住戸を表現し、住戸内階段や勾配屋根はありません。",
      "中央廊下の幅は1400 mmです。玄関の奥行350 mmの下駄箱を除くと通行幅は1050 mmです。",
      "洋室2室の北側に高窓、LDK南側にバルコニーへ通じる掃き出し引き戸2組を配置します。戸境壁には側窓を設けません。",
      "玄関の段差は境界線で示します。モデルの床仕上げ基準はZ=0で、防水・排水勾配・敷居の構造は未モデル化です。",
      "室内の建具開口は700/750/800 mmです。引き戸は壁付けレールの概念とし、壁際の収納スペースを確保します。寸法は下地開口です。",
      "浴室1400 × 1800 mm、洗面脱衣室1600 × 1800 mm、トイレ1000 × 1800 mmは計画上の確保寸法です。",
      "天井スラブとバルコニー腰壁は外形のみを表現します。建具・収納・衛生設備は概念的な配置で、製品は未選定です。",
      "天井スラブはZ=2500〜2700 mmです。階高基準2800 mmまでの残り100 mmの層間構成は未モデル化です。",
      "構造、採光・換気、防火避難、設備シャフト、バルコニー隔て板、建築確認申請要件は未検証です。",
    ],
  },
  en: {
    bedroom1: 'Bedroom 1', title: 'Japanese apartment · 2LDK', description: 'An approximately 65 m² Japanese 2LDK apartment concept with two bedrooms, living/dining/kitchen, separate wet rooms and a south balcony. Explore the parametric model, plan and CAD files.',
    plan: 'Apartment plan', planTitle: '2LDK apartment plan', pdf: 'Open apartment PDF drawing', complete: 'Whole apartment', interior: 'Apartment interior',
    areaNote: 'Net room areas include cabinets and fixtures. The balcony is listed separately and excluded from the interior total. The 65.52 m² outline area is not net internal area.',
    parameterNote: 'Demonstration assumptions. 65.52 m² is outline area; the balcony is additional. Structure and services have not been designed.',
    preview: 'Japanese 2LDK apartment plan with room names, clear dimensions, areas, doors and windows, a 7800 × 8400-millimetre outline and south balcony.',
    summary: 'A single-level Japanese 2LDK apartment concept. The 7800 × 8400 mm outline, 2800 mm storey height, 2500 mm clear height and 7800 × 1500 mm south balcony are demonstration assumptions. 65.52 m² is outline area, not net internal area; the balcony is additional.',
    drafting: 'Includes DXF with editable Japanese room names and dimensions, solid STEP, grouped GLB and an A3 PDF. This is a concept draft; structure, fire safety, services, site conditions and regulatory compliance have not been verified.',
    planDetail: 'Single-level 2LDK with editable Japanese room names and dimensions, including the south balcony.', pdfTitle: 'Apartment A3 floor plan', pdfDetail: 'One Japanese drawing, A3 landscape at 1:50. Print at actual size.',
    assumptions: [
      "The 7800 × 8400 mm outline, 2800 mm storey height, 2500 mm clear height and all detail dimensions are demonstration assumptions.",
      "65.52 m² is the outline projection including external walls and partitions. It is not registered property area, exclusive-use area or statutory floor area.",
      "56.54 m² is the sum of clear room boundaries. It includes cabinet and fixture footprints and excludes all walls and the balcony.",
      "The 11.70 m² balcony is a separate 7800 × 1500 mm concept slab projection, including the parapet footprint.",
      "Entry from a north shared corridor, a south balcony and the north direction are display assumptions. No site or whole-building information was supplied.",
      "External and party walls are 200 mm, partitions 100 mm and slabs 200 mm. The model is one dwelling with no internal stairs or pitched roof.",
      "The central hallway is 1400 mm wide. A 350 mm-deep entrance shoe cabinet leaves a 1050 mm passage.",
      "Both bedrooms have high north windows. Two full-height sliding door sets connect the south LDK to the balcony; the party walls have no side windows.",
      "The entrance level change is indicated by a boundary line. All finished floors use Z=0; waterproofing, drainage falls and threshold construction are not modelled.",
      "Internal door openings are 700/750/800 mm. Sliding doors use a concept wall-mounted track with space beside the opening. Dimensions are rough openings.",
      "The bathroom 1400 × 1800 mm, washroom/changing room 1600 × 1800 mm and toilet 1000 × 1800 mm are reserved concept dimensions.",
      "The ceiling slab and balcony parapets represent their outlines only. Doors, windows, cabinets and sanitary fixtures are placeholders; products have not been selected.",
      "The ceiling slab spans Z=2500–2700 mm. The remaining 100 mm of construction to the 2800 mm storey datum is not modelled.",
      "Structure, daylight and ventilation, fire safety and escape, service shafts, balcony separation panels and Japanese building-approval requirements have not been verified.",
    ],
  },
};

export function modelCopy(copy: Messages, locale: Locale, id: ModelId): Messages {
  if (id === 'house') return copy;
  const text = apartment[locale];
  return {
    ...copy,
    app: { ...copy.app, title: text.title, description: text.description, tabs: { ...copy.app.tabs, '1f': text.plan } },
    model: { ...copy.model, title: text.title },
    groups: { ...copy.groups, F1: text.interior },
    rooms: { ...copy.rooms, master: text.bedroom1 },
    presets: { ...copy.presets, exterior: text.complete },
    parameters: { ...copy.parameters, note: text.parameterNote },
    plan: { ...copy.plan, sidebar: text.planTitle, viewer: text.planTitle, title: text.planTitle, openPdf: text.pdf, areaNote: text.areaNote, previewPlan: text.preview, previewSheet: text.preview },
    downloads: { ...copy.downloads, title: `${text.title} · ${copy.downloads.title}`, summary: text.summary, drafting: text.drafting,
      files: { ...copy.downloads.files, first: { title: text.plan, detail: text.planDetail }, pdf: { title: text.pdfTitle, detail: text.pdfDetail } } },
    assumptions: text.assumptions,
  };
}
